version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # 호스트의 3307 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fastapi_network

  fastapi:
    build:
      context: .
    container_name: fastapi-container
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
    - .:/app  # 현재 디렉토리를 컨테이너의 /app에 마운트
    depends_on:
      - db
    networks:
      - fastapi_network

volumes:
  mysql_data:

networks:
  fastapi_network:
